director_uuid: 93c01d2d-a2a5-49d8-8d02-389fd223a9cf

name: torus

jobs:
- name: etcd_z1
  instances: 1
  networks:
  - name: torus_1
    static_ips:
    - 10.244.5.4
  resource_pool: torus_z1
  persistent_disk: 1024
  templates:
  - release: torus
    name: etcd

- name: torus_z1
  instances: 3
  networks:
  - name: torus_1
    static_ips:
    - 10.244.5.5
    - 10.244.5.6
    - 10.244.5.7
  resource_pool: torus_z1
  persistent_disk: 1024
  templates:
  - release: torus
    name: torus

networks:
- type: manual
  name: torus_1
  subnets:
  - reserved:
    - 10.244.5.2-10.244.5.3
    - 10.244.5.12-10.244.5.254
    static:
    - 10.244.5.4
    - 10.244.5.5
    - 10.244.5.6
    - 10.244.5.7
    - 10.244.5.8
    cloud_properties:
      name: random
    gateway: 10.244.5.1
    range: 10.244.5.0/24

compilation:
  workers: 3
  cloud_properties: {}
  network: torus_1
  reuse_compilation_vms: true

update:
  canary_watch_time: 1000-180000
  max_in_flight: 1
  serial: true
  update_watch_time: 1000-180000
  canaries: 1

resource_pools:
- name: torus_z1
  network: torus_1
  cloud_properties: {}
  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

properties:
  etcd:
    address: 10.244.5.4:4001
  torus:
    etcd_address: 10.244.5.4:4001
    size: 512MiB

releases:
- name: torus
  version: latest

